### ISSUE TITLE
Support for vit model from timm

### ISSUE THREAD

**Issue by vivian96385** [topal-team/rockmate#2]
Hi,

Very interesting work! Thanks for releasing your code.
I'm trying to use vision transformer based model these days. However, I encountered a problem when using it.
I use vit_tiny_patch16_224 from timm and there's an error that it fails with the embedding part of it. 
Do you have any idea about what may cause the error while generating the graph?

The error 
```
Traceback (most recent call last):
  File "/app/rockmate/check_rk_model.py", line 19, in <module>
    rk_vit_tiny = Rockmate(vit_tiny, sample, m_budget)
  File "/app/rockmate/rockmate/src/main.py", line 68, in __init__
    self.rkgb_res = rkgb.make_all_graphs(
  File "/app/rockmate/rkgb/src/main.py", line 202, in make_all_graphs
    if bool_kg: kg = Ktools.S_to_K(sg,model,device=device)
  File "/app/rockmate/rkgb/src/Ktools.py", line 625, in S_to_K
    return aux_build_S_to_K(sg,model,prev_kg = None)
  File "/app/rockmate/rkgb/src/Ktools.py", line 549, in aux_build_S_to_K
    handle_node(sn)
  File "/app/rockmate/rkgb/src/Ktools.py", line 515, in handle_node
    ins.measure_fwd()
  File "/app/rockmate/rkgb/src/utils/def_inspection.py", line 294, in measure_fwd
    time_run_fwd = self.measure_time(fct_run_fwd)
  File "/app/rockmate/rkgb/src/utils/def_inspection.py", line 233, in measure_time
    t = self.timer.measure(fct)
  File "/app/rockmate/rkgb/src/utils/imports_from_rotor.py", line 93, in measure
    func()
  File "/app/rockmate/rkgb/src/utils/def_inspection.py", line 266, in fct_run_fwd
    exec(self.code_run_fwd, self.our_global, self.tmp_local)
  File "<string>", line 5, in <module>
RuntimeError: The expanded size of the tensor (-1) isn't allowed in a leading, non-existing dimension 1
```

and my code is as follows
```
import torch
import torch.nn as nn
import torch.optim as optim
from rockmate import Rockmate
import torchvision
#from torchvision.models import resnet18
import torchvision.transforms as transforms
from tqdm import tqdm
import timm

device = torch.device("cuda")

#resnet = resnet18().cuda()
vit_tiny = timm.create_model('vit_tiny_patch16_224',num_classes=100,pretrained=True).cuda()
#optimizer = torch.optim.Adam(resnet.parameters())
sample = torch.randn([100, 3, 224, 224]).cuda()
m_budget = 2 * 1024**3 # 2GB

rk_vit_tiny = Rockmate(vit_tiny, sample, m_budget)
```

Thanks!

**Comment by Nagael** [comment]
Hello,

Thank you for the report! We currently use `torch.jit` to extract the code of the models. Unfortunately, `jit` fails on some models, and while I have not investigated this one in detail, I suspect that this is the source of your problem.

We are currently working on moving to `torch.compiler` based on TorchDynamo which hopefully will solve your issue. Stay tuned, we will ping this issue when we have a fix.

**Comment by vivian96385** [comment]
Thanks for your reply, and i'm looking forward to your updates.

Good lucks!
